/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.CasillaCalle;
import civitas.Jugador;
import java.util.ArrayList;

/**
 *
 * @author celiaa
 */
public class JugadorPanel extends javax.swing.JPanel {
    
    private Jugador jugador;
    
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }
    
    public void setJugador(Jugador j){
        jugador = j;
        nombrePanel.setText(jugador.getNombre());
        saldoPanel.setText(Float.toString(jugador.getSaldo()));
        if(jugador.isEspeculador()){
            especuladorPanel.setText("SI");
        }else{
            especuladorPanel.setText("NO");
        }
        //especuladorPanel.setText(Boolean.toString(jugador.esEspeculador()));
        
        repaint();
        revalidate(); 
        
        rellenaPropiedades(jugador.getPropiedades());
    }
    
    private void rellenaPropiedades(ArrayList<CasillaCalle> lista){
        //Se elimina la info antigua
        propiedadesPanel.removeAll();
        //Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for(CasillaCalle t : lista){
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            
            propiedadesPanel.add(vistaPropiedad);
            //propiedadesPanel.setVisible(true);
            vistaPropiedad.setVisible(true);
        }
        //Se fuerza la actualizacion visual del panel propiedades y del panel jugador
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        nombrePanel = new javax.swing.JTextField();
        saldo = new javax.swing.JLabel();
        saldoPanel = new javax.swing.JTextField();
        especulador = new javax.swing.JLabel();
        propiedadesPanel = new javax.swing.JPanel();
        especuladorPanel = new javax.swing.JTextField();

        nombre.setText("Nombre");
        add(nombre);

        nombrePanel.setEditable(false);
        nombrePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePanelActionPerformed(evt);
            }
        });
        add(nombrePanel);

        saldo.setText("Saldo");
        add(saldo);

        saldoPanel.setEditable(false);
        saldoPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoPanelActionPerformed(evt);
            }
        });
        add(saldoPanel);

        especulador.setText("Especulador");
        add(especulador);

        especuladorPanel.setEditable(false);
        especuladorPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especuladorPanelActionPerformed(evt);
            }
        });
        propiedadesPanel.add(especuladorPanel);

        add(propiedadesPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void nombrePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePanelActionPerformed

    private void saldoPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoPanelActionPerformed

    private void especuladorPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especuladorPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especuladorPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel especulador;
    private javax.swing.JTextField especuladorPanel;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombrePanel;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JLabel saldo;
    private javax.swing.JTextField saldoPanel;
    // End of variables declaration//GEN-END:variables
}
